### ISSUE TITLE
Enchance

### ISSUE THREAD

**Issue by Brodvd** [vaclavmuller/AudacityThemeVersionConverter#1]
HI @vaclavmuller , thanks for this project!😄 
Can you add the support to the others theme version (like audacity 3.0.0 ...)?
And also you can add in the file  `readme.md`  of this project the libreries needs (pillow...)?

**Comment by Brodvd** [comment]
@vaclavmuller  fantastic work!

**Comment by vaclavmuller** [comment]
> HI @vaclavmuller , thanks for this project!😄 Can you add the support to the others theme version (like audacity 3.0.0 ...)? And also you can add in the file `readme.md` of this project the libreries needs (pillow...)?

The problem was that I didn't know how to compile older versions of Audacity to get and compare the ImageCache of those versions. The current version of the converter can handle many versions of this program. I'm working on gradually incorporating more.

**Comment by Brodvd** [comment]
Thanks, good luck!
